WINDOW_WIDTH = 700
WINDOW_HEIGHT = 430

window = {
	"name" : "BattlePassWindow",
	"x" : SCREEN_WIDTH - WINDOW_WIDTH - 20,
	"y" : SCREEN_HEIGHT - WINDOW_HEIGHT - 90,
	"style" : ("movable", "float",),
	"width" : WINDOW_WIDTH,
	"height" : WINDOW_HEIGHT,
	"children" :
	(
		{
			"name" : "board",
			"type" : "board_with_titlebar",
			"x" : 0,
			"y" : 0,
			"width" : WINDOW_WIDTH,
			"height" : WINDOW_HEIGHT,
			"title" : "Battle Pass Gorevleri",
			"children" :
			(
				{
					"name" : "LeftPanel",
					"type" : "bar",
					"x" : 10,
					"y" : 34,
					"width" : 340,
					"height" : 340,
					"color" : 0xAA000000,
				},
				{
					"name" : "LeftHeaderLine",
					"type" : "horizontalbar",
					"x" : 14,
					"y" : 96,
					"width" : 332,
				},
				{
					"name" : "DetailPanel",
					"type" : "bar",
					"x" : 354,
					"y" : 34,
					"width" : 200,
					"height" : 340,
					"color" : 0xAA000000,
				},
				{
					"name" : "StatusBox",
					"type" : "bar",
					"x" : 360,
					"y" : 82,
					"width" : 188,
					"height" : 48,
					"color" : 0x55000000,
				},
				{
					"name" : "ProgressBox",
					"type" : "bar",
					"x" : 360,
					"y" : 136,
					"width" : 188,
					"height" : 56,
					"color" : 0x55000000,
				},
				{
					"name" : "BonusBox",
					"type" : "bar",
					"x" : 360,
					"y" : 198,
					"width" : 188,
					"height" : 76,
					"color" : 0x55000000,
				},
				{
					"name" : "RewardBox",
					"type" : "bar",
					"x" : 360,
					"y" : 278,
					"width" : 188,
					"height" : 54,
					"color" : 0x55000000,
				},
				{
					"name" : "PreviewPanel",
					"type" : "bar",
					"x" : 558,
					"y" : 34,
					"width" : 132,
					"height" : 340,
					"color" : 0xAA000000,
				},
				{
					"name" : "PreviewInnerPanel",
					"type" : "bar",
					"x" : 564,
					"y" : 62,
					"width" : 120,
					"height" : 266,
					"color" : 0x55000000,
				},
				{
					"name" : "SeasonText",
					"type" : "text",
					"x" : 16,
					"y" : 40,
					"text" : "Sezon: 0",
				},
				{
					"name" : "LevelText",
					"type" : "text",
					"x" : 16,
					"y" : 58,
					"text" : "Tamamlanan: 0",
				},
				{
					"name" : "PointText",
					"type" : "text",
					"x" : 16,
					"y" : 76,
					"text" : "Toplam Gorev: 0",
				},
				{
					"name" : "StatusText",
					"type" : "text",
					"x" : 366,
					"y" : 88,
					"text" : "Durum: -",
				},
				{
					"name" : "CategoryText",
					"type" : "text",
					"x" : 366,
					"y" : 108,
					"text" : "Kategori: PVM Gorevleri",
				},
				{
					"name" : "DetailTitleText",
					"type" : "text",
					"x" : 366,
					"y" : 142,
					"text" : "Gorev Detayi",
				},
				{
					"name" : "DetailProgressText",
					"type" : "text",
					"x" : 366,
					"y" : 162,
					"text" : "Ilerleme: 0/0",
				},
				{
					"name" : "BonusLine1",
					"type" : "text",
					"x" : 366,
					"y" : 204,
					"text" : "-",
				},
				{
					"name" : "BonusLine2",
					"type" : "text",
					"x" : 366,
					"y" : 222,
					"text" : "-",
				},
				{
					"name" : "BonusLine3",
					"type" : "text",
					"x" : 366,
					"y" : 240,
					"text" : "-",
				},
				{
					"name" : "RewardSlot",
					"type" : "slot",
					"x" : 366,
					"y" : 290,
					"width" : 32,
					"height" : 32,
					"image" : "d:/ymir work/ui/public/slot_base.sub",
					"slot" : (
						{"index" : 0, "x" : 0, "y" : 0, "width" : 32, "height" : 32},
					),
				},
				{
					"name" : "RewardNameText",
					"type" : "text",
					"x" : 404,
					"y" : 292,
					"text" : "Odul: -",
				},
				{
					"name" : "RewardCountText",
					"type" : "text",
					"x" : 404,
					"y" : 310,
					"text" : "x0",
				},
				{
					"name" : "ClaimButton",
					"type" : "button",
					"x" : 360,
					"y" : 338,
					"text" : "Secili Gorev Odulu",
					"default_image" : "d:/ymir work/ui/public/middle_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/middle_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/middle_button_03.sub",
				},
				{
					"name" : "PreviewTitleText",
					"type" : "text",
					"x" : 566,
					"y" : 42,
					"text" : "Model Onizleme",
				},
				{
					"name" : "TabPvmButton",
					"type" : "button",
					"x" : 14,
					"y" : 382,
					"default_image" : "d:/ymir work/ui/public/small_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/small_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/small_button_03.sub",
				},
				{
					"name" : "TabGeneralButton",
					"type" : "button",
					"x" : 64,
					"y" : 382,
					"default_image" : "d:/ymir work/ui/public/small_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/small_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/small_button_03.sub",
				},
				{
					"name" : "TabHintText",
					"type" : "text",
					"x" : 120,
					"y" : 390,
					"text" : "Sekmeler: PvM / Genel",
				},
			),
		},
	),
}
