WINDOW_WIDTH = 700
WINDOW_HEIGHT = 430

window = {
	"name" : "BattlePassWindow",
	"x" : SCREEN_WIDTH - WINDOW_WIDTH - 20,
	"y" : SCREEN_HEIGHT - WINDOW_HEIGHT - 90,
	"style" : ("movable", "float",),
	"width" : WINDOW_WIDTH,
	"height" : WINDOW_HEIGHT,
	"children" :
	(
		{
			"name" : "board",
			"type" : "board_with_titlebar",
			"x" : 0,
			"y" : 0,
			"width" : WINDOW_WIDTH,
			"height" : WINDOW_HEIGHT,
			"title" : "Battle Pass Gorevleri",
			"children" :
			(
				{
					"name" : "LeftPanel",
					"type" : "bar",
					"x" : 10,
					"y" : 34,
					"width" : 338,
					"height" : 378,
					"color" : 0xAA000000,
				},
				{
					"name" : "DetailPanel",
					"type" : "bar",
					"x" : 352,
					"y" : 34,
					"width" : 198,
					"height" : 378,
					"color" : 0xAA000000,
				},
				{
					"name" : "PreviewPanel",
					"type" : "bar",
					"x" : 554,
					"y" : 34,
					"width" : 136,
					"height" : 378,
					"color" : 0xAA000000,
				},
				{
					"name" : "SeasonText",
					"type" : "text",
					"x" : 16,
					"y" : 40,
					"text" : "Sezon: 0",
				},
				{
					"name" : "LevelText",
					"type" : "text",
					"x" : 16,
					"y" : 58,
					"text" : "Level: 0",
				},
				{
					"name" : "PointText",
					"type" : "text",
					"x" : 16,
					"y" : 76,
					"text" : "Puan: 0/100",
				},
				{
					"name" : "StatusText",
					"type" : "text",
					"x" : 360,
					"y" : 42,
					"text" : "Durum: -",
				},
				{
					"name" : "DetailTitleText",
					"type" : "text",
					"x" : 360,
					"y" : 62,
					"text" : "Gorev Detayi",
				},
				{
					"name" : "DetailProgressText",
					"type" : "text",
					"x" : 360,
					"y" : 82,
					"text" : "Ilerleme: 0/0",
				},
				{
					"name" : "BonusTitleText",
					"type" : "text",
					"x" : 360,
					"y" : 112,
					"text" : "Bonuslar",
				},
				{
					"name" : "BonusLine1",
					"type" : "text",
					"x" : 360,
					"y" : 132,
					"text" : "-",
				},
				{
					"name" : "BonusLine2",
					"type" : "text",
					"x" : 360,
					"y" : 150,
					"text" : "-",
				},
				{
					"name" : "BonusLine3",
					"type" : "text",
					"x" : 360,
					"y" : 168,
					"text" : "-",
				},
				{
					"name" : "PreviewTitleText",
					"type" : "text",
					"x" : 564,
					"y" : 42,
					"text" : "Model Onizleme",
				},
				{
					"name" : "RewardHintText",
					"type" : "text",
					"x" : 360,
					"y" : 312,
					"text" : "Odul secilen seviyeden alinir.",
				},
				{
					"name" : "FreeClaimButton",
					"type" : "button",
					"x" : 360,
					"y" : 340,
					"text" : "Free Odul Al",
					"default_image" : "d:/ymir work/ui/public/large_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/large_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/large_button_03.sub",
				},
				{
					"name" : "PremiumClaimButton",
					"type" : "button",
					"x" : 360,
					"y" : 370,
					"text" : "Premium Odul Al",
					"default_image" : "d:/ymir work/ui/public/large_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/large_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/large_button_03.sub",
				},
			),
		},
	),
}
