WINDOW_WIDTH = 700
WINDOW_HEIGHT = 430

window = {
	"name" : "BattlePassWindow",
	"x" : SCREEN_WIDTH - WINDOW_WIDTH - 20,
	"y" : SCREEN_HEIGHT - WINDOW_HEIGHT - 90,
	"style" : ("movable", "float",),
	"width" : WINDOW_WIDTH,
	"height" : WINDOW_HEIGHT,
	"children" :
	(
		{
			"name" : "board",
			"type" : "board_with_titlebar",
			"x" : 0,
			"y" : 0,
			"width" : WINDOW_WIDTH,
			"height" : WINDOW_HEIGHT,
			"title" : "Battle Pass Gorevleri",
			"children" :
			(
				{
					"name" : "LeftPanel",
					"type" : "bar",
					"x" : 10,
					"y" : 34,
					"width" : 340,
					"height" : 340,
					"color" : 0xAA000000,
				},
				{
					"name" : "DetailPanel",
					"type" : "bar",
					"x" : 354,
					"y" : 34,
					"width" : 200,
					"height" : 340,
					"color" : 0xAA000000,
				},
				{
					"name" : "PreviewPanel",
					"type" : "bar",
					"x" : 558,
					"y" : 34,
					"width" : 132,
					"height" : 340,
					"color" : 0xAA000000,
				},
				{
					"name" : "SeasonText",
					"type" : "text",
					"x" : 16,
					"y" : 40,
					"text" : "Sezon: 0",
				},
				{
					"name" : "LevelText",
					"type" : "text",
					"x" : 16,
					"y" : 58,
					"text" : "Tamamlanan: 0",
				},
				{
					"name" : "PointText",
					"type" : "text",
					"x" : 16,
					"y" : 76,
					"text" : "Toplam Gorev: 0",
				},
				{
					"name" : "StatusText",
					"type" : "text",
					"x" : 362,
					"y" : 42,
					"text" : "Durum: -",
				},
				{
					"name" : "CategoryText",
					"type" : "text",
					"x" : 362,
					"y" : 60,
					"text" : "Kategori: PVM Gorevleri",
				},
				{
					"name" : "DetailTitleText",
					"type" : "text",
					"x" : 362,
					"y" : 88,
					"text" : "Gorev Detayi",
				},
				{
					"name" : "DetailProgressText",
					"type" : "text",
					"x" : 362,
					"y" : 108,
					"text" : "Ilerleme: 0/0",
				},
				{
					"name" : "BonusLine1",
					"type" : "text",
					"x" : 362,
					"y" : 138,
					"text" : "-",
				},
				{
					"name" : "BonusLine2",
					"type" : "text",
					"x" : 362,
					"y" : 156,
					"text" : "-",
				},
				{
					"name" : "BonusLine3",
					"type" : "text",
					"x" : 362,
					"y" : 174,
					"text" : "-",
				},
				{
					"name" : "RewardSlot",
					"type" : "slot",
					"x" : 362,
					"y" : 206,
					"width" : 32,
					"height" : 32,
					"image" : "d:/ymir work/ui/public/slot_base.sub",
					"slot" : (
						{"index" : 0, "x" : 0, "y" : 0, "width" : 32, "height" : 32},
					),
				},
				{
					"name" : "RewardNameText",
					"type" : "text",
					"x" : 400,
					"y" : 210,
					"text" : "Odul VNUM: 0",
				},
				{
					"name" : "RewardCountText",
					"type" : "text",
					"x" : 400,
					"y" : 228,
					"text" : "x0",
				},
				{
					"name" : "ClaimButton",
					"type" : "button",
					"x" : 362,
					"y" : 266,
					"text" : "Gorev Odulunu Al",
					"default_image" : "d:/ymir work/ui/public/large_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/large_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/large_button_03.sub",
				},
				{
					"name" : "PreviewTitleText",
					"type" : "text",
					"x" : 566,
					"y" : 42,
					"text" : "Model Onizleme",
				},
				{
					"name" : "TabPvmButton",
					"type" : "button",
					"x" : 14,
					"y" : 380,
					"default_image" : "d:/ymir work/ui/public/slot_cover_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/slot_cover_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/slot_cover_button_03.sub",
				},
				{
					"name" : "TabGeneralButton",
					"type" : "button",
					"x" : 50,
					"y" : 380,
					"default_image" : "d:/ymir work/ui/public/slot_cover_button_01.sub",
					"over_image" : "d:/ymir work/ui/public/slot_cover_button_02.sub",
					"down_image" : "d:/ymir work/ui/public/slot_cover_button_03.sub",
				},
				{
					"name" : "TabHintText",
					"type" : "text",
					"x" : 88,
					"y" : 388,
					"text" : "Sol alt butonlar: PVM / Genel",
				},
			),
		},
	),
}
